- name: OpenStack end to end configuration
  hosts: localhost
  connection: local
  gather_facts: false
  become: false

  tasks:

    - name: Fetch Instance Info
      os_server_info:
        cloud: openstack
        region_name: regionOne
      register: r_os_servers
    debug:   r_os_servers